# Generated by Django 4.1.5 on 2023-02-01 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirlinesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airlineName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AirportsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FlightModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('distination', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='FlightsSystem.airportsmodel')),
                ('orgin', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='FlightsSystem.airportsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PassengersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=10)),
                ('last', models.CharField(max_length=20)),
                ('passportCountry', models.CharField(max_length=30)),
                ('passportNumber', models.IntegerField(max_length=30)),
                ('passengerPic', models.BinaryField(blank=True, null=True)),
                ('flights', models.ManyToManyField(blank=True, related_name='passengers', to='FlightsSystem.flightmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TicketsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketType', models.CharField(choices=[('Economy', 'Economy Class'), ('Business', 'Business Class'), ('VIP', 'VIP Class')], max_length=30)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='FlightsSystem.airlinesmodel')),
                ('passenger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passenger', to='FlightsSystem.passengersmodel')),
            ],
        ),
        migrations.AddField(
            model_name='airlinesmodel',
            name='flights',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatedailine', to='FlightsSystem.flightmodel'),
        ),
    ]
