# Generated by Django 4.1.5 on 2023-02-01 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FlightsSystem', '0003_alter_airlinesmodel_flights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airlinesmodel',
            name='flights',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatedailine', to='FlightsSystem.flightmodel'),
        ),
    ]
