# Generated by Django 4.1.5 on 2023-02-01 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FlightsSystem', '0005_alter_airlinesmodel_flights'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightmodel',
            old_name='orgin',
            new_name='origin',
        ),
    ]
