# Generated by Django 4.1.5 on 2023-02-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightsSystem', '0006_rename_orgin_flightmodel_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengersmodel',
            name='passengerPic',
        ),
        migrations.AddField(
            model_name='passengersmodel',
            name='passport_photo',
            field=models.ImageField(null=True, upload_to='passport_photos/'),
        ),
    ]
