# Generated by Django 4.1.5 on 2023-02-03 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FlightsSystem', '0007_remove_passengersmodel_passengerpic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airlinesmodel',
            name='flights',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airline', to='FlightsSystem.flightmodel'),
        ),
        migrations.AlterField(
            model_name='passengersmodel',
            name='passport_photo',
            field=models.ImageField(blank=True, default='passenger_photos/default.jpg', null=True, upload_to='passport_photos/'),
        ),
        migrations.AlterField(
            model_name='ticketsmodel',
            name='passenger',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='FlightsSystem.passengersmodel'),
        ),
    ]
