# Generated by Django 4.1.5 on 2023-02-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightsSystem', '0008_alter_airlinesmodel_flights_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengersmodel',
            name='flights',
            field=models.ManyToManyField(blank=True, null=True, related_name='passengers', to='FlightsSystem.flightmodel'),
        ),
        migrations.AlterField(
            model_name='passengersmodel',
            name='passport_photo',
            field=models.ImageField(blank=True, default='passenger_photos/default.jpg', upload_to='passport_photos/'),
        ),
    ]
