# Generated by Django 4.1.5 on 2023-02-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightsSystem', '0009_alter_passengersmodel_flights_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengersmodel',
            name='passport_photo',
            field=models.ImageField(blank=True, default='passenger_photos/default.jpg', null=True, upload_to='passport_photos/'),
        ),
    ]
