# Generated by Django 4.1.5 on 2023-02-11 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FlightsSystem', '0010_alter_passengersmodel_passport_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsmodel',
            name='flight',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='FlightsSystem.flightmodel'),
        ),
        migrations.AlterField(
            model_name='passengersmodel',
            name='flights',
            field=models.ManyToManyField(blank=True, related_name='passengers', to='FlightsSystem.flightmodel'),
        ),
    ]
