# Generated by Django 4.1.5 on 2023-02-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightsSystem', '0011_ticketsmodel_flight_alter_passengersmodel_flights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengersmodel',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
