# Generated by Django 4.1.5 on 2023-02-19 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FlightsSystem', '0012_alter_passengersmodel_passport_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengersmodel',
            name='passportNumber',
        ),
    ]
