name: Testing
on: push

jobs: test
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run django Unit Test
      run: 
        pip3 install --user django
        python manage.py test