name: Test Workflow
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Django Unit Test
        run: |
          pip3 install --user django
          cd AirlineSystem
          python manage.py test
